name: flutter_resume
description: B. Cihan Cengiz resume.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  timelines: ^0.0.2+1
  font_awesome_flutter: ^8.11.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  build_web_compilers: ^2.12.2

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.jpg
    - assets/flutter.png
