name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: flutter web build
        run: | 
          flutter config --enable-web
          flutter pub get
          flutter build web

      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build/web
          GITHUB_TOKEN: ${{ secrets.RESUME_ACTIONS }}
